%% GARE POLICY ITERATION WITH DISTURBANCE-AWARE THESIS EXTENSION
%
% This script retains the model-based GARE policy-iteration core and
% appends the disturbance-aware command-channel offset extension.
%
% Nominal system:
%
%   x(k+1) = Ad*x(k) + B*u_P(k) + E*u_E(k)
%
% Nominal saddle policies:
%
%   u_P(k) = L*x(k)     minimizing player / pursuer
%   u_E(k) = K*x(k)     maximizing player / evader
%
% Realized biased inputs:
%
%   u_P_actual(k) = u_P_command(k) + b_P
%   u_E_actual(k) = u_E_command(k) + b_E
%
% Affine compensation:
%
%   u_P_command(k) = L*x(k) - b_P_hat
%   u_E_command(k) = K*x(k) - b_E_hat
%
% Main publication figures:
%
%   1. Convergence of Model-Based GARE Policy Iteration
%   2. Cost-Weighted State-Deviation Recovery
%   3. Late-Time Command-Channel Bias Compensation
%   4. Monte Carlo Validation of Command-Offset Estimates
%
% The full numerical workspace, CSV summaries, and text report are
% saved automatically.
%
% No local functions or additional MATLAB files are required.

clear;
close all;
clc;

%% Reproducibility

rng(7,'twister');

%% ============================================================
%  PUBLICATION FIGURE SETTINGS
%  ============================================================

font_name = 'Times New Roman';
font_size = 11;

figure_background = [1 1 1];
axes_background = [1 1 1];

text_color = [0.10 0.10 0.10];
axis_color = [0.18 0.18 0.18];
grid_color = [0.84 0.84 0.84];
legend_edge_color = [0.68 0.68 0.68];

annotation_background = [1 1 1];
annotation_edge = [0.78 0.78 0.78];

set(groot,'defaultFigureColor',figure_background);
set(groot,'defaultAxesColor',axes_background);
set(groot,'defaultAxesXColor',axis_color);
set(groot,'defaultAxesYColor',axis_color);
set(groot,'defaultAxesZColor',axis_color);

set(groot,'defaultAxesFontName',font_name);
set(groot,'defaultTextFontName',font_name);
set(groot,'defaultAxesFontSize',font_size);

set(groot,'defaultAxesLineWidth',0.85);
set(groot,'defaultAxesGridColor',grid_color);
set(groot,'defaultAxesGridAlpha',0.28);
set(groot,'defaultAxesMinorGridAlpha',0.10);

set(groot,'defaultTextColor',text_color);
set(groot,'defaultLineLineWidth',1.45);

set(groot,'defaultTextInterpreter','tex');
set(groot,'defaultAxesTickLabelInterpreter','tex');
set(groot,'defaultLegendInterpreter','tex');

%% Results Folder

results_folder = fullfile(pwd,'GARE_PI_Thesis_Results');

if ~exist(results_folder,'dir')
    mkdir(results_folder);
end

%% Remove Files Produced by Earlier Executions

generated_patterns = { ...
    'Figure_*.png', ...
    'Figure_*.fig', ...
    'GARE_PI_*.csv', ...
    'GARE_PI_*.mat', ...
    'GARE_PI_*.txt'};

for pattern_index = 1:length(generated_patterns)

    generated_files = dir(fullfile( ...
        results_folder,generated_patterns{pattern_index}));

    for file_index = 1:length(generated_files)

        delete(fullfile( ...
            generated_files(file_index).folder, ...
            generated_files(file_index).name));

    end

end

fprintf('\n');
fprintf('============================================================\n');
fprintf('GARE POLICY ITERATION WITH DISTURBANCE-AWARE EXTENSION\n');
fprintf('============================================================\n');
fprintf('Results folder:\n%s\n\n',results_folder);

%% ============================================================
%  ORIGINAL DISCRETE-TIME ZERO-SUM BENCHMARK
%  ============================================================

Ad = [0.9064880,  0.0816012, -0.000500000;
      0.0741349,  0.9012100, -0.000708383;
      0,          0,          0.132655000];

B = [-0.00150808;
     -0.00960000;
      0.86734500];

E = [0.00951892;
     0.000383730;
     0];

C = [1 0 -1];

nx = size(Ad,1);
nuP = size(B,2);
nuE = size(E,2);

if nuP ~= 1 || nuE ~= 1

    error(['This benchmark expects one scalar pursuer input ', ...
           'and one scalar evader input.']);

end

%% Original Zero-Sum Cost Parameters

Q = eye(3);

RP = 1;

gamma = 1;

RE = gamma^2;

%% Policy-Iteration Settings

policy_tolerance = 1e-7;

maximum_iterations = 2000;

conditioning_tolerance = 1e-12;

%% Original Initialization

P = eye(nx);

L = zeros(nuP,nx);

K = zeros(nuE,nx);

iteration = 0;

Acl_initial = Ad+B*L+E*K;

initial_spectral_radius = max(abs(eig(Acl_initial)));

if initial_spectral_radius >= 1

    error(['The initial policy pair is not admissible. ', ...
           'rho(Acl_initial) = %.12g.'], ...
           initial_spectral_radius);

end

fprintf('Initial closed-loop spectral radius: %.12g\n', ...
    initial_spectral_radius);

%% Allocate Iteration Histories

P_error_history = nan(maximum_iterations,1);

L_error_history = nan(maximum_iterations,1);

K_error_history = nan(maximum_iterations,1);

spectral_radius_history = nan(maximum_iterations,1);

game_rcond_history = nan(maximum_iterations,1);

converged = false;

%% ============================================================
%  ORIGINAL MODEL-BASED POLICY ITERATION
%  ============================================================

while iteration < maximum_iterations

    iteration = iteration+1;

    P_previous = P;

    L_previous = L;

    K_previous = K;

    %% Policy Evaluation

    A_iteration = ...
        Ad+B*L_previous+E*K_previous;

    current_spectral_radius = ...
        max(abs(eig(A_iteration)));

    if current_spectral_radius >= 1

        error(['Policy evaluation failed at iteration %d. ', ...
               'The current closed-loop matrix is not ', ...
               'Schur stable. rho = %.12g.'], ...
               iteration,current_spectral_radius);

    end

    policy_stage_matrix = ...
        Q ...
        + L_previous'*RP*L_previous ...
        - K_previous'*RE*K_previous;

    policy_stage_matrix = ...
        0.5*(policy_stage_matrix+policy_stage_matrix');

    % MATLAB dlyap(A_iteration',S) solves:
    %
    %   A_iteration'*P*A_iteration - P + S = 0.

    P = dlyap(A_iteration',policy_stage_matrix);

    P = 0.5*(P+P');

    %% Policy Improvement

    H_PP = RP+B'*P*B;

    H_PE = B'*P*E;

    H_EP = E'*P*B;

    H_EE = E'*P*E-RE;

    H_Px = B'*P*Ad;

    H_Ex = E'*P*Ad;

    pursuer_update_matrix = ...
        H_PP-H_PE*(H_EE\H_EP);

    pursuer_update_vector = ...
        H_PE*(H_EE\H_Ex)-H_Px;

    evader_update_matrix = ...
        H_EE-H_EP*(H_PP\H_PE);

    evader_update_vector = ...
        H_EP*(H_PP\H_Px)-H_Ex;

    if rcond(pursuer_update_matrix) <= conditioning_tolerance

        error(['The pursuer policy update is poorly ', ...
               'conditioned at iteration %d.'],iteration);

    end

    if rcond(evader_update_matrix) <= conditioning_tolerance

        error(['The evader policy update is poorly ', ...
               'conditioned at iteration %d.'],iteration);

    end

    L = pursuer_update_matrix\pursuer_update_vector;

    K = evader_update_matrix\evader_update_vector;

    %% Iteration Diagnostics

    A_updated = Ad+B*L+E*K;

    P_error_history(iteration) = ...
        norm(P-P_previous,'fro');

    L_error_history(iteration) = ...
        norm(L-L_previous,'fro');

    K_error_history(iteration) = ...
        norm(K-K_previous,'fro');

    spectral_radius_history(iteration) = ...
        max(abs(eig(A_updated)));

    game_matrix_iteration = ...
        [RP+B'*P*B, B'*P*E;
         E'*P*B,    E'*P*E-RE];

    game_rcond_history(iteration) = ...
        rcond(game_matrix_iteration);

    %% Original Stopping Criterion

    if P_error_history(iteration) < policy_tolerance

        converged = true;

        break;

    end

end

%% Trim Histories

P_error_history = ...
    P_error_history(1:iteration);

L_error_history = ...
    L_error_history(1:iteration);

K_error_history = ...
    K_error_history(1:iteration);

spectral_radius_history = ...
    spectral_radius_history(1:iteration);

game_rcond_history = ...
    game_rcond_history(1:iteration);

if ~converged

    warning(['Policy iteration reached the maximum number ', ...
             'of iterations before convergence.']);

end

%% ============================================================
%  FINAL NOMINAL VERIFICATION
%  ============================================================

Acl = Ad+B*L+E*K;

closed_loop_spectral_radius = ...
    max(abs(eig(Acl)));

%% Final Game Blocks

H_PP = RP+B'*P*B;

H_PE = B'*P*E;

H_EP = E'*P*B;

H_EE = E'*P*E-RE;

H_Px = B'*P*Ad;

H_Ex = E'*P*Ad;

game_matrix = ...
    [H_PP, H_PE;
     H_EP, H_EE];

state_coupling = ...
    [H_Px;
     H_Ex];

game_matrix_rcond = ...
    rcond(game_matrix);

%% Saddle Curvature

pursuer_curvature_minimum = ...
    min(real(eig(0.5*(H_PP+H_PP'))));

evader_schur = ...
    H_EE-H_EP*(H_PP\H_PE);

evader_schur = ...
    0.5*(evader_schur+evader_schur');

evader_curvature_maximum = ...
    max(real(eig(evader_schur)));

%% GARE Residual

GARE_right_side = ...
    Q ...
    + Ad'*P*Ad ...
    - [Ad'*P*B,Ad'*P*E] ...
      *(game_matrix\state_coupling);

GARE_right_side = ...
    0.5*(GARE_right_side+GARE_right_side');

GARE_residual_matrix = ...
    P-GARE_right_side;

GARE_residual = ...
    norm(GARE_residual_matrix,'fro');

normalized_GARE_residual = ...
    GARE_residual/(1+norm(P,'fro'));

%% Lyapunov Residual

Lyapunov_right_side = ...
    Q ...
    + L'*RP*L ...
    - K'*RE*K ...
    + Acl'*P*Acl;

Lyapunov_right_side = ...
    0.5*(Lyapunov_right_side+Lyapunov_right_side');

Lyapunov_residual_matrix = ...
    P-Lyapunov_right_side;

Lyapunov_residual = ...
    norm(Lyapunov_residual_matrix,'fro');

normalized_Lyapunov_residual = ...
    Lyapunov_residual/(1+norm(P,'fro'));

%% Numerical Validity Checks

if closed_loop_spectral_radius >= 1

    error(['The converged closed-loop matrix is not ', ...
           'Schur stable. rho = %.12g.'], ...
           closed_loop_spectral_radius);

end

if pursuer_curvature_minimum <= 0

    error(['The minimizing-player curvature condition ', ...
           'is not satisfied.']);

end

if evader_curvature_maximum >= 0

    error(['The maximizing-player curvature condition ', ...
           'is not satisfied.']);

end

if game_matrix_rcond <= conditioning_tolerance

    error(['The converged game matrix is singular or ', ...
           'poorly conditioned.']);

end

%% Nominal Terminal Report

fprintf('\n');
fprintf('NOMINAL GARE POLICY-ITERATION RESULT\n');
fprintf('------------------------------------------------------------\n');
fprintf('Converged:                         %d\n',converged);
fprintf('Iterations:                        %d\n',iteration);
fprintf('Closed-loop spectral radius:       %.12e\n', ...
    closed_loop_spectral_radius);
fprintf('GARE residual:                     %.12e\n', ...
    GARE_residual);
fprintf('Normalized GARE residual:          %.12e\n', ...
    normalized_GARE_residual);
fprintf('Lyapunov residual:                 %.12e\n', ...
    Lyapunov_residual);
fprintf('Normalized Lyapunov residual:      %.12e\n', ...
    normalized_Lyapunov_residual);
fprintf('Game-matrix reciprocal condition:  %.12e\n', ...
    game_matrix_rcond);
fprintf('Pursuer curvature minimum:         %.12e\n', ...
    pursuer_curvature_minimum);
fprintf('Evader curvature maximum:          %.12e\n', ...
    evader_curvature_maximum);

fprintf('\nPursuer/Minimizing Gain L:\n');
disp(L);

fprintf('Evader/Maximizing Gain K:\n');
disp(K);

fprintf('Value Matrix P:\n');
disp(P);

%% ============================================================
%  DISTURBANCE-AWARE THESIS EXTENSION
%  ============================================================

bP_true = 0.040;

bE_true = -0.010;

bias_true = ...
    [bP_true;
     bE_true];

%% Calibration Settings

Ncal = 250;

calibration_noise_std = 1e-4;

x_cal = zeros(nx,Ncal+1);

x_cal(:,1) = ...
    [0.6;
    -0.3;
     0.2];

transition_residual = ...
    zeros(nx,Ncal);

%% Model-Based Calibration Experiment

for calibration_index = 1:Ncal

    uP_calibration_command = ...
        0.35*sin(0.17*calibration_index) ...
        + 0.18*cos(0.41*calibration_index);

    uE_calibration_command = ...
        0.30*cos(0.13*calibration_index) ...
        - 0.15*sin(0.37*calibration_index);

    uP_calibration_actual = ...
        uP_calibration_command+bP_true;

    uE_calibration_actual = ...
        uE_calibration_command+bE_true;

    calibration_noise = ...
        calibration_noise_std*randn(nx,1);

    x_cal(:,calibration_index+1) = ...
        Ad*x_cal(:,calibration_index) ...
        + B*uP_calibration_actual ...
        + E*uE_calibration_actual ...
        + calibration_noise;

    transition_residual(:,calibration_index) = ...
        x_cal(:,calibration_index+1) ...
        - Ad*x_cal(:,calibration_index) ...
        - B*uP_calibration_command ...
        - E*uE_calibration_command;

end

%% Offset Identifiability

bias_map = [B E];

bias_map_rank = rank(bias_map);

required_bias_rank = nuP+nuE;

bias_map_condition_number = ...
    cond(bias_map);

if bias_map_rank < required_bias_rank

    error(['The pursuer and evader offsets are not ', ...
           'separately identifiable from [B E].']);

end

%% Primary Offset Estimate

mean_transition_residual = ...
    mean(transition_residual,2);

bias_estimate = ...
    bias_map\mean_transition_residual;

bP_hat = bias_estimate(1);

bE_hat = bias_estimate(2);

bias_estimation_error = ...
    bias_estimate-bias_true;

bP_absolute_error = ...
    abs(bP_hat-bP_true);

bE_absolute_error = ...
    abs(bE_hat-bE_true);

bP_percentage_error = ...
    100*bP_absolute_error/max(abs(bP_true),eps);

bE_percentage_error = ...
    100*bE_absolute_error/max(abs(bE_true),eps);

%% Theoretical Estimator Covariance
%
% For independent isotropic calibration noise:
%
%   Cov(b_hat)
%       = sigma^2/Ncal * (M'*M)^(-1),
%
% where:
%
%   M = [B E].

theoretical_bias_covariance = ...
    (calibration_noise_std^2/Ncal) ...
    *((bias_map'*bias_map)\eye(required_bias_rank));

theoretical_bias_covariance = ...
    0.5*(theoretical_bias_covariance ...
    + theoretical_bias_covariance');

theoretical_bias_std = ...
    sqrt(max(diag(theoretical_bias_covariance),0));

theoretical_bias_95_lower = ...
    bias_true-1.96*theoretical_bias_std;

theoretical_bias_95_upper = ...
    bias_true+1.96*theoretical_bias_std;

%% Monte Carlo Estimator Validation

monte_carlo_trials = 1000;

mean_noise_trials = ...
    calibration_noise_std/sqrt(Ncal) ...
    *randn(nx,monte_carlo_trials);

mean_residual_trials = ...
    repmat( ...
    bias_map*bias_true, ...
    1,monte_carlo_trials) ...
    + mean_noise_trials;

monte_carlo_bias_estimates = ...
    bias_map\mean_residual_trials;

monte_carlo_bias_mean = ...
    mean(monte_carlo_bias_estimates,2);

% Standard deviation of individual calibration estimates.

monte_carlo_bias_std = ...
    std(monte_carlo_bias_estimates,0,2);

% Standard error of the reported Monte Carlo sample mean.

monte_carlo_mean_standard_error = ...
    monte_carlo_bias_std/sqrt(monte_carlo_trials);

monte_carlo_bias_error = ...
    monte_carlo_bias_mean-bias_true;

monte_carlo_bias_rmse = ...
    sqrt(mean( ...
    (monte_carlo_bias_estimates ...
    - repmat( ...
    bias_true,1,monte_carlo_trials)).^2,2));

fprintf('\n');
fprintf('COMMAND-OFFSET CALIBRATION\n');
fprintf('------------------------------------------------------------\n');
fprintf('Calibration samples:                 %d\n',Ncal);
fprintf('Bias-map rank:                       %d of %d\n', ...
    bias_map_rank,required_bias_rank);
fprintf('Bias-map condition number:           %.12e\n', ...
    bias_map_condition_number);
fprintf('True pursuer offset:                 %+.12e\n', ...
    bP_true);
fprintf('Estimated pursuer offset:            %+.12e\n', ...
    bP_hat);
fprintf('Pursuer absolute error:              %.12e\n', ...
    bP_absolute_error);
fprintf('Pursuer percentage error:            %.6f %%\n', ...
    bP_percentage_error);
fprintf('True evader offset:                  %+.12e\n', ...
    bE_true);
fprintf('Estimated evader offset:             %+.12e\n', ...
    bE_hat);
fprintf('Evader absolute error:               %.12e\n', ...
    bE_absolute_error);
fprintf('Evader percentage error:             %.6f %%\n', ...
    bE_percentage_error);

fprintf('\n');
fprintf('MONTE CARLO ESTIMATOR VALIDATION\n');
fprintf('------------------------------------------------------------\n');
fprintf('Trials:                              %d\n', ...
    monte_carlo_trials);
fprintf('Pursuer individual-estimate std:     %.12e\n', ...
    monte_carlo_bias_std(1));
fprintf('Pursuer Monte Carlo mean SE:         %.12e\n', ...
    monte_carlo_mean_standard_error(1));
fprintf('Pursuer estimator RMSE:              %.12e\n', ...
    monte_carlo_bias_rmse(1));
fprintf('Evader individual-estimate std:      %.12e\n', ...
    monte_carlo_bias_std(2));
fprintf('Evader Monte Carlo mean SE:          %.12e\n', ...
    monte_carlo_mean_standard_error(2));
fprintf('Evader estimator RMSE:               %.12e\n', ...
    monte_carlo_bias_rmse(2));

%% ============================================================
%  FOUR MATCHED CLOSED-LOOP CASES
%  ============================================================

Nsim = 500;

number_of_cases = 4;

case_names = { ...
    'Nominal', ...
    'Without Compensation', ...
    'Estimated Compensation', ...
    'Exact Compensation'};

x_initial = ...
    [10;
      5;
     -2];

%% Plant Offsets

plant_bias_P = ...
    [0, ...
     bP_true, ...
     bP_true, ...
     bP_true];

plant_bias_E = ...
    [0, ...
     bE_true, ...
     bE_true, ...
     bE_true];

%% Command Compensation

command_compensation_P = ...
    [0, ...
     0, ...
     bP_hat, ...
     bP_true];

command_compensation_E = ...
    [0, ...
     0, ...
     bE_hat, ...
     bE_true];

%% Residual Command Offsets

residual_bias_P = ...
    plant_bias_P-command_compensation_P;

residual_bias_E = ...
    plant_bias_E-command_compensation_E;

%% Affine Closed-Loop Forcing

affine_forcing = ...
    B*residual_bias_P ...
    + E*residual_bias_E;

%% Allocate Closed-Loop Arrays

x_case = ...
    zeros(nx,Nsim+1,number_of_cases);

uP_command = ...
    zeros(nuP,Nsim,number_of_cases);

uE_command = ...
    zeros(nuE,Nsim,number_of_cases);

uP_actual = ...
    zeros(nuP,Nsim,number_of_cases);

uE_actual = ...
    zeros(nuE,Nsim,number_of_cases);

state_cost = ...
    zeros(Nsim,number_of_cases);

pursuer_cost = ...
    zeros(Nsim,number_of_cases);

evader_cost = ...
    zeros(Nsim,number_of_cases);

game_stage_cost = ...
    zeros(Nsim,number_of_cases);

%% Simulate the Four Cases

for case_index = 1:number_of_cases

    x_case(:,1,case_index) = x_initial;

    for time_index = 1:Nsim

        %% Policy Commands

        uP_command(:,time_index,case_index) = ...
            L*x_case(:,time_index,case_index) ...
            - command_compensation_P(case_index);

        uE_command(:,time_index,case_index) = ...
            K*x_case(:,time_index,case_index) ...
            - command_compensation_E(case_index);

        %% Realized Inputs

        uP_actual(:,time_index,case_index) = ...
            uP_command(:,time_index,case_index) ...
            + plant_bias_P(case_index);

        uE_actual(:,time_index,case_index) = ...
            uE_command(:,time_index,case_index) ...
            + plant_bias_E(case_index);

        %% Plant Propagation

        x_case(:,time_index+1,case_index) = ...
            Ad*x_case(:,time_index,case_index) ...
            + B*uP_actual(:,time_index,case_index) ...
            + E*uE_actual(:,time_index,case_index);

        %% Cost Components

        state_cost(time_index,case_index) = ...
            x_case(:,time_index,case_index)' ...
            *Q ...
            *x_case(:,time_index,case_index);

        pursuer_cost(time_index,case_index) = ...
            uP_actual(:,time_index,case_index)' ...
            *RP ...
            *uP_actual(:,time_index,case_index);

        evader_cost(time_index,case_index) = ...
            uE_actual(:,time_index,case_index)' ...
            *RE ...
            *uE_actual(:,time_index,case_index);

        game_stage_cost(time_index,case_index) = ...
            state_cost(time_index,case_index) ...
            + pursuer_cost(time_index,case_index) ...
            - evader_cost(time_index,case_index);

    end

end

%% Finite-Window Cost Components

state_cost_total = ...
    sum(state_cost,1)';

pursuer_cost_total = ...
    sum(pursuer_cost,1)';

evader_cost_total = ...
    sum(evader_cost,1)';

game_cost_total = ...
    sum(game_stage_cost,1)';

signed_cost_change = ...
    game_cost_total-game_cost_total(1);

absolute_cost_recovery_error = ...
    abs(signed_cost_change);

%% ============================================================
%  COST-WEIGHTED STATE DEVIATION FROM NOMINAL
%  ============================================================
%
% The plotted metric is:
%
%   ||d_k||_Q = sqrt(d_k'*Q*d_k),
%
% where:
%
%   d_k = x_case(k)-x_nominal(k).
%
% Because Q = I_3, this equals the Euclidean norm for the current
% benchmark while remaining consistent with the state metric used
% in the game objective.

state_deviation = ...
    zeros(nx,Nsim+1,number_of_cases);

weighted_state_deviation = ...
    zeros(Nsim+1,number_of_cases);

maximum_weighted_state_deviation = ...
    zeros(number_of_cases,1);

for case_index = 1:number_of_cases

    state_deviation(:,:,case_index) = ...
        x_case(:,:,case_index)-x_case(:,:,1);

    for time_index = 1:Nsim+1

        deviation_vector = ...
            state_deviation(:,time_index,case_index);

        weighted_state_deviation(time_index,case_index) = ...
            sqrt(max(real( ...
            deviation_vector'*Q*deviation_vector),0));

    end

    maximum_weighted_state_deviation(case_index) = ...
        max(weighted_state_deviation(:,case_index));

end

estimated_error_reduction_percent = ...
    100*(1 ...
    - maximum_weighted_state_deviation(3)/...
    max(maximum_weighted_state_deviation(2),eps));

exact_error_reduction_percent = ...
    100*(1 ...
    - maximum_weighted_state_deviation(4)/...
    max(maximum_weighted_state_deviation(2),eps));

%% ============================================================
%  ANALYTICAL AFFINE-DEVIATION VERIFICATION
%  ============================================================

analytical_deviation = ...
    zeros(nx,Nsim+1,number_of_cases);

for case_index = 1:number_of_cases

    for time_index = 1:Nsim

        analytical_deviation(:,time_index+1,case_index) = ...
            Acl*analytical_deviation(:,time_index,case_index) ...
            + affine_forcing(:,case_index);

    end

end

analytical_mismatch = ...
    zeros(Nsim+1,number_of_cases);

maximum_analytical_mismatch = ...
    zeros(number_of_cases,1);

for case_index = 1:number_of_cases

    for time_index = 1:Nsim+1

        mismatch_vector = ...
            state_deviation(:,time_index,case_index) ...
            - analytical_deviation(:,time_index,case_index);

        analytical_mismatch(time_index,case_index) = ...
            norm(mismatch_vector,2);

    end

    maximum_analytical_mismatch(case_index) = ...
        max(analytical_mismatch(:,case_index));

end

%% Asymptotic Affine Deviation

equilibrium_matrix = ...
    eye(nx)-Acl;

if rcond(equilibrium_matrix) <= conditioning_tolerance

    warning(['The affine equilibrium matrix I-Acl is ', ...
             'poorly conditioned.']);

end

asymptotic_deviation = ...
    equilibrium_matrix\affine_forcing;

asymptotic_weighted_deviation = ...
    zeros(number_of_cases,1);

for case_index = 1:number_of_cases

    asymptotic_weighted_deviation(case_index) = ...
        sqrt(max(real( ...
        asymptotic_deviation(:,case_index)' ...
        *Q ...
        *asymptotic_deviation(:,case_index)),0));

end

maximum_exact_trajectory_error = ...
    maximum_weighted_state_deviation(4);

%% Input-Channel Signals and Residuals

uP_policy = ...
    zeros(Nsim,number_of_cases);

uE_policy = ...
    zeros(Nsim,number_of_cases);

uP_command_matrix = ...
    zeros(Nsim,number_of_cases);

uE_command_matrix = ...
    zeros(Nsim,number_of_cases);

uP_actual_matrix = ...
    zeros(Nsim,number_of_cases);

uE_actual_matrix = ...
    zeros(Nsim,number_of_cases);

for case_index = 1:number_of_cases

    uP_policy(:,case_index) = ...
        (L*x_case(:,1:Nsim,case_index))';

    uE_policy(:,case_index) = ...
        (K*x_case(:,1:Nsim,case_index))';

    uP_command_matrix(:,case_index) = ...
        reshape(uP_command(1,:,case_index),[],1);

    uE_command_matrix(:,case_index) = ...
        reshape(uE_command(1,:,case_index),[],1);

    uP_actual_matrix(:,case_index) = ...
        reshape(uP_actual(1,:,case_index),[],1);

    uE_actual_matrix(:,case_index) = ...
        reshape(uE_actual(1,:,case_index),[],1);

end

uP_channel_error = ...
    uP_actual_matrix-uP_policy;

uE_channel_error = ...
    uE_actual_matrix-uE_policy;

maximum_uP_channel_error = ...
    max(abs(uP_channel_error),[],1)';

maximum_uE_channel_error = ...
    max(abs(uE_channel_error),[],1)';

%% Verification Warnings

if maximum_exact_trajectory_error > 1e-12

    warning(['Exact compensation did not reproduce the ', ...
             'nominal trajectory to numerical precision.']);

end

if max(maximum_analytical_mismatch) > 1e-11

    warning(['The analytical affine recurrence did not ', ...
             'match the simulated deviation to the expected ', ...
             'numerical tolerance.']);

end

if maximum_weighted_state_deviation(3) >= ...
        maximum_weighted_state_deviation(2)

    warning(['Estimated compensation did not reduce the ', ...
             'maximum cost-weighted state deviation.']);

end

%% Closed-Loop Terminal Report

fprintf('\n');
fprintf('DISTURBANCE-AWARE CLOSED-LOOP RESULTS\n');
fprintf('------------------------------------------------------------\n');

for case_index = 1:number_of_cases

    fprintf('\n%s\n',case_names{case_index});

    fprintf('  State-cost component:             %.12e\n', ...
        state_cost_total(case_index));

    fprintf('  Pursuer-cost component:           %.12e\n', ...
        pursuer_cost_total(case_index));

    fprintf('  Evader-cost component:            %.12e\n', ...
        evader_cost_total(case_index));

    fprintf('  Signed finite-window game cost:   %.12e\n', ...
        game_cost_total(case_index));

    fprintf('  Signed cost change from nominal:  %+.12e\n', ...
        signed_cost_change(case_index));

    fprintf('  Absolute cost-recovery error:     %.12e\n', ...
        absolute_cost_recovery_error(case_index));

    fprintf('  Maximum cost-weighted deviation:  %.12e\n', ...
        maximum_weighted_state_deviation(case_index));

    fprintf('  Maximum analytical mismatch:      %.12e\n', ...
        maximum_analytical_mismatch(case_index));

end

fprintf('\n');
fprintf('Estimated-compensation state-error reduction: %.6f %%\n', ...
    estimated_error_reduction_percent);
fprintf('Exact-compensation state-error reduction:     %.6f %%\n', ...
    exact_error_reduction_percent);
fprintf('Maximum simulated/analytical mismatch:        %.12e\n', ...
    max(maximum_analytical_mismatch));

%% ============================================================
%  SAVE NUMERICAL RESULTS
%  ============================================================

summary_table = table( ...
    converged, ...
    iteration, ...
    closed_loop_spectral_radius, ...
    GARE_residual, ...
    normalized_GARE_residual, ...
    Lyapunov_residual, ...
    normalized_Lyapunov_residual, ...
    game_matrix_rcond, ...
    pursuer_curvature_minimum, ...
    evader_curvature_maximum, ...
    bP_true, ...
    bP_hat, ...
    bP_hat-bP_true, ...
    bP_percentage_error, ...
    bE_true, ...
    bE_hat, ...
    bE_hat-bE_true, ...
    bE_percentage_error, ...
    bias_map_rank, ...
    bias_map_condition_number, ...
    theoretical_bias_std(1), ...
    theoretical_bias_std(2), ...
    monte_carlo_trials, ...
    monte_carlo_bias_mean(1), ...
    monte_carlo_bias_std(1), ...
    monte_carlo_mean_standard_error(1), ...
    monte_carlo_bias_rmse(1), ...
    monte_carlo_bias_mean(2), ...
    monte_carlo_bias_std(2), ...
    monte_carlo_mean_standard_error(2), ...
    monte_carlo_bias_rmse(2), ...
    estimated_error_reduction_percent, ...
    exact_error_reduction_percent, ...
    maximum_exact_trajectory_error, ...
    max(maximum_analytical_mismatch), ...
    'VariableNames',{ ...
    'Converged', ...
    'Iterations', ...
    'ClosedLoopSpectralRadius', ...
    'GAREResidual', ...
    'NormalizedGAREResidual', ...
    'LyapunovResidual', ...
    'NormalizedLyapunovResidual', ...
    'GameMatrixReciprocalCondition', ...
    'PursuerCurvatureMinimum', ...
    'EvaderCurvatureMaximum', ...
    'TruePursuerOffset', ...
    'EstimatedPursuerOffset', ...
    'PursuerOffsetSignedError', ...
    'PursuerOffsetPercentError', ...
    'TrueEvaderOffset', ...
    'EstimatedEvaderOffset', ...
    'EvaderOffsetSignedError', ...
    'EvaderOffsetPercentError', ...
    'BiasMapRank', ...
    'BiasMapConditionNumber', ...
    'TheoreticalPursuerEstimateStd', ...
    'TheoreticalEvaderEstimateStd', ...
    'MonteCarloTrials', ...
    'MonteCarloPursuerMean', ...
    'MonteCarloPursuerIndividualStd', ...
    'MonteCarloPursuerMeanStandardError', ...
    'MonteCarloPursuerRMSE', ...
    'MonteCarloEvaderMean', ...
    'MonteCarloEvaderIndividualStd', ...
    'MonteCarloEvaderMeanStandardError', ...
    'MonteCarloEvaderRMSE', ...
    'EstimatedStateErrorReductionPercent', ...
    'ExactStateErrorReductionPercent', ...
    'MaximumExactTrajectoryError', ...
    'MaximumAnalyticalMismatch'});

writetable( ...
    summary_table, ...
    fullfile(results_folder,'GARE_PI_Summary.csv'));

execution_case_table = table( ...
    case_names', ...
    state_cost_total, ...
    pursuer_cost_total, ...
    evader_cost_total, ...
    game_cost_total, ...
    signed_cost_change, ...
    absolute_cost_recovery_error, ...
    maximum_weighted_state_deviation, ...
    asymptotic_weighted_deviation, ...
    maximum_analytical_mismatch, ...
    maximum_uP_channel_error, ...
    maximum_uE_channel_error, ...
    'VariableNames',{ ...
    'ExecutionCase', ...
    'StateCostComponent', ...
    'PursuerCostComponent', ...
    'EvaderCostComponent', ...
    'SignedFiniteWindowGameCost', ...
    'SignedCostChangeFromNominal', ...
    'AbsoluteCostRecoveryError', ...
    'MaximumCostWeightedStateDeviation', ...
    'AsymptoticCostWeightedDeviation', ...
    'MaximumAnalyticalMismatch', ...
    'MaximumPursuerChannelError', ...
    'MaximumEvaderChannelError'});

writetable( ...
    execution_case_table, ...
    fullfile(results_folder,'GARE_PI_Execution_Cases.csv'));

offset_estimator_table = table( ...
    {'Pursuer';'Evader'}, ...
    bias_true, ...
    bias_estimate, ...
    bias_estimation_error, ...
    theoretical_bias_std, ...
    theoretical_bias_95_lower, ...
    theoretical_bias_95_upper, ...
    monte_carlo_bias_mean, ...
    monte_carlo_bias_std, ...
    monte_carlo_mean_standard_error, ...
    monte_carlo_bias_error, ...
    monte_carlo_bias_rmse, ...
    'VariableNames',{ ...
    'CommandChannel', ...
    'TrueOffset', ...
    'PrimaryEstimate', ...
    'PrimarySignedError', ...
    'TheoreticalIndividualEstimateStd', ...
    'Theoretical95Lower', ...
    'Theoretical95Upper', ...
    'MonteCarloMean', ...
    'MonteCarloIndividualEstimateStd', ...
    'MonteCarloMeanStandardError', ...
    'MonteCarloSignedError', ...
    'MonteCarloRMSE'});

writetable( ...
    offset_estimator_table, ...
    fullfile(results_folder,'GARE_PI_Offset_Estimator.csv'));

%% Save Complete MATLAB Results

save( ...
    fullfile(results_folder,'GARE_PI_Complete_Results.mat'), ...
    'Ad', ...
    'B', ...
    'E', ...
    'C', ...
    'Q', ...
    'RP', ...
    'RE', ...
    'gamma', ...
    'P', ...
    'L', ...
    'K', ...
    'Acl', ...
    'closed_loop_spectral_radius', ...
    'GARE_residual_matrix', ...
    'GARE_residual', ...
    'normalized_GARE_residual', ...
    'Lyapunov_residual_matrix', ...
    'Lyapunov_residual', ...
    'normalized_Lyapunov_residual', ...
    'game_matrix', ...
    'game_matrix_rcond', ...
    'pursuer_curvature_minimum', ...
    'evader_curvature_maximum', ...
    'P_error_history', ...
    'L_error_history', ...
    'K_error_history', ...
    'spectral_radius_history', ...
    'game_rcond_history', ...
    'bP_true', ...
    'bE_true', ...
    'bP_hat', ...
    'bE_hat', ...
    'bias_true', ...
    'bias_estimate', ...
    'bias_estimation_error', ...
    'bias_map', ...
    'bias_map_rank', ...
    'bias_map_condition_number', ...
    'theoretical_bias_covariance', ...
    'theoretical_bias_std', ...
    'theoretical_bias_95_lower', ...
    'theoretical_bias_95_upper', ...
    'x_cal', ...
    'transition_residual', ...
    'monte_carlo_trials', ...
    'monte_carlo_bias_estimates', ...
    'monte_carlo_bias_mean', ...
    'monte_carlo_bias_std', ...
    'monte_carlo_mean_standard_error', ...
    'monte_carlo_bias_error', ...
    'monte_carlo_bias_rmse', ...
    'x_case', ...
    'uP_command', ...
    'uE_command', ...
    'uP_actual', ...
    'uE_actual', ...
    'uP_policy', ...
    'uE_policy', ...
    'uP_command_matrix', ...
    'uE_command_matrix', ...
    'uP_actual_matrix', ...
    'uE_actual_matrix', ...
    'uP_channel_error', ...
    'uE_channel_error', ...
    'state_cost', ...
    'pursuer_cost', ...
    'evader_cost', ...
    'game_stage_cost', ...
    'state_cost_total', ...
    'pursuer_cost_total', ...
    'evader_cost_total', ...
    'game_cost_total', ...
    'signed_cost_change', ...
    'absolute_cost_recovery_error', ...
    'state_deviation', ...
    'weighted_state_deviation', ...
    'maximum_weighted_state_deviation', ...
    'analytical_deviation', ...
    'analytical_mismatch', ...
    'maximum_analytical_mismatch', ...
    'asymptotic_deviation', ...
    'asymptotic_weighted_deviation', ...
    'estimated_error_reduction_percent', ...
    'exact_error_reduction_percent', ...
    'summary_table', ...
    'execution_case_table', ...
    'offset_estimator_table');

%% Plain-Text Report

report_path = ...
    fullfile(results_folder,'GARE_PI_Report.txt');

report_id = ...
    fopen(report_path,'w');

if report_id == -1

    warning('The plain-text report could not be created.');

else

    fprintf(report_id, ...
        'GARE POLICY ITERATION WITH DISTURBANCE-AWARE EXTENSION\n');

    fprintf(report_id, ...
        '============================================================\n\n');

    fprintf(report_id,'NOMINAL POLICY ITERATION\n');
    fprintf(report_id,'------------------------------------------------------------\n');
    fprintf(report_id,'Converged: %d\n',converged);
    fprintf(report_id,'Iterations: %d\n',iteration);

    fprintf(report_id, ...
        'Closed-loop spectral radius: %.16e\n', ...
        closed_loop_spectral_radius);

    fprintf(report_id, ...
        'GARE residual: %.16e\n', ...
        GARE_residual);

    fprintf(report_id, ...
        'Normalized GARE residual: %.16e\n', ...
        normalized_GARE_residual);

    fprintf(report_id, ...
        'Lyapunov residual: %.16e\n', ...
        Lyapunov_residual);

    fprintf(report_id, ...
        'Normalized Lyapunov residual: %.16e\n', ...
        normalized_Lyapunov_residual);

    fprintf(report_id, ...
        'Game-matrix reciprocal condition: %.16e\n', ...
        game_matrix_rcond);

    fprintf(report_id, ...
        'Pursuer curvature minimum: %.16e\n', ...
        pursuer_curvature_minimum);

    fprintf(report_id, ...
        'Evader curvature maximum: %.16e\n\n', ...
        evader_curvature_maximum);

    fprintf(report_id,'Pursuer Gain L:\n');
    fprintf(report_id,'%.16e %.16e %.16e\n',L);

    fprintf(report_id,'\nEvader Gain K:\n');
    fprintf(report_id,'%.16e %.16e %.16e\n',K);

    fprintf(report_id,'\nValue Matrix P:\n');

    for row_index = 1:nx

        fprintf(report_id, ...
            '%.16e %.16e %.16e\n', ...
            P(row_index,:));

    end

    fprintf(report_id,'\nOFFSET CALIBRATION\n');
    fprintf(report_id,'------------------------------------------------------------\n');

    fprintf(report_id, ...
        'True pursuer offset: %.16e\n',bP_true);

    fprintf(report_id, ...
        'Estimated pursuer offset: %.16e\n',bP_hat);

    fprintf(report_id, ...
        'Pursuer percentage error: %.8f %%\n', ...
        bP_percentage_error);

    fprintf(report_id, ...
        'True evader offset: %.16e\n',bE_true);

    fprintf(report_id, ...
        'Estimated evader offset: %.16e\n',bE_hat);

    fprintf(report_id, ...
        'Evader percentage error: %.8f %%\n', ...
        bE_percentage_error);

    fprintf(report_id, ...
        'Theoretical pursuer estimate std: %.16e\n', ...
        theoretical_bias_std(1));

    fprintf(report_id, ...
        'Theoretical evader estimate std: %.16e\n', ...
        theoretical_bias_std(2));

    fprintf(report_id, ...
        'Monte Carlo pursuer individual std: %.16e\n', ...
        monte_carlo_bias_std(1));

    fprintf(report_id, ...
        'Monte Carlo evader individual std: %.16e\n', ...
        monte_carlo_bias_std(2));

    fprintf(report_id, ...
        'Monte Carlo pursuer mean SE: %.16e\n', ...
        monte_carlo_mean_standard_error(1));

    fprintf(report_id, ...
        'Monte Carlo evader mean SE: %.16e\n', ...
        monte_carlo_mean_standard_error(2));

    fprintf(report_id,'\nEXECUTION CASES\n');
    fprintf(report_id,'------------------------------------------------------------\n');

    for case_index = 1:number_of_cases

        fprintf(report_id,'\n%s\n',case_names{case_index});

        fprintf(report_id, ...
            'State-cost component: %.16e\n', ...
            state_cost_total(case_index));

        fprintf(report_id, ...
            'Pursuer-cost component: %.16e\n', ...
            pursuer_cost_total(case_index));

        fprintf(report_id, ...
            'Evader-cost component: %.16e\n', ...
            evader_cost_total(case_index));

        fprintf(report_id, ...
            'Signed game cost: %.16e\n', ...
            game_cost_total(case_index));

        fprintf(report_id, ...
            'Signed cost change: %.16e\n', ...
            signed_cost_change(case_index));

        fprintf(report_id, ...
            'Maximum cost-weighted deviation: %.16e\n', ...
            maximum_weighted_state_deviation(case_index));

        fprintf(report_id, ...
            'Maximum pursuer channel error: %.16e\n', ...
            maximum_uP_channel_error(case_index));

        fprintf(report_id, ...
            'Maximum evader channel error: %.16e\n', ...
            maximum_uE_channel_error(case_index));

        fprintf(report_id, ...
            'Maximum analytical mismatch: %.16e\n', ...
            maximum_analytical_mismatch(case_index));

    end

    fprintf(report_id, ...
        '\nEstimated state-error reduction: %.8f %%\n', ...
        estimated_error_reduction_percent);

    fprintf(report_id, ...
        'Exact state-error reduction: %.8f %%\n', ...
        exact_error_reduction_percent);

    fprintf(report_id, ...
        'Maximum analytical mismatch: %.16e\n', ...
        max(maximum_analytical_mismatch));

    fclose(report_id);

end

%% ============================================================
%  FIGURE COLOR PALETTE
%  ============================================================

nominal_color = [0.0000 0.4470 0.7410];

uncompensated_color = [0.8500 0.3250 0.0980];

estimated_color = [0.4660 0.6740 0.1880];

exact_color = [0.4940 0.1840 0.5560];

policy_color = [0.12 0.12 0.12];

command_color = [0.0000 0.4470 0.7410];

realized_color = [0.4660 0.6740 0.1880];

theoretical_color = [0.6350 0.0780 0.1840];

%% ============================================================
%  FIGURE 1: POLICY-ITERATION CONVERGENCE
%  ============================================================

numerical_floor = 1e-18;

P_plot = ...
    max(P_error_history,numerical_floor);

L_plot = ...
    max(L_error_history,numerical_floor);

K_plot = ...
    max(K_error_history,numerical_floor);

all_convergence_values = [ ...
    P_plot(:);
    L_plot(:);
    K_plot(:)];

convergence_minimum = ...
    min(all_convergence_values);

convergence_maximum = ...
    max(all_convergence_values);

if ~isfinite(convergence_minimum) || ...
        convergence_minimum <= 0

    convergence_minimum = ...
        numerical_floor;

end

if ~isfinite(convergence_maximum) || ...
        convergence_maximum <= convergence_minimum

    convergence_maximum = ...
        100*convergence_minimum;

end

convergence_lower_limit = ...
    10^floor(log10(convergence_minimum));

convergence_upper_limit = ...
    10^ceil(log10(convergence_maximum));

if convergence_upper_limit <= convergence_lower_limit

    convergence_upper_limit = ...
        10*convergence_lower_limit;

end

figure_1 = figure( ...
    'Color','w', ...
    'InvertHardcopy','off', ...
    'Renderer','painters', ...
    'Position',[100 100 980 620], ...
    'Name','GARE Policy Iteration Convergence');

axes_1 = axes(figure_1);

semilogy( ...
    axes_1, ...
    1:iteration, ...
    P_plot, ...
    '-o', ...
    'Color',nominal_color, ...
    'MarkerFaceColor',nominal_color, ...
    'MarkerSize',6.5, ...
    'LineWidth',1.55);

hold(axes_1,'on');

semilogy( ...
    axes_1, ...
    1:iteration, ...
    L_plot, ...
    '--s', ...
    'Color',uncompensated_color, ...
    'MarkerFaceColor','w', ...
    'MarkerSize',6.5, ...
    'LineWidth',1.50);

semilogy( ...
    axes_1, ...
    1:iteration, ...
    K_plot, ...
    '-.^', ...
    'Color',estimated_color, ...
    'MarkerFaceColor','w', ...
    'MarkerSize',7, ...
    'LineWidth',1.50);

set(axes_1, ...
    'Color','w', ...
    'XColor',axis_color, ...
    'YColor',axis_color, ...
    'FontName',font_name, ...
    'FontSize',font_size, ...
    'LineWidth',0.85, ...
    'Box','on', ...
    'XGrid','off', ...
    'YGrid','on', ...
    'XMinorGrid','off', ...
    'YMinorGrid','off', ...
    'GridColor',grid_color, ...
    'GridAlpha',0.28);

xlim(axes_1,[1,max(iteration,2)]);

ylim(axes_1,[ ...
    convergence_lower_limit, ...
    convergence_upper_limit]);

xticks(axes_1,1:iteration);

xlabel( ...
    axes_1, ...
    'Policy-iteration index', ...
    'Color',axis_color);

ylabel( ...
    axes_1, ...
    'Successive-iteration change', ...
    'Color',axis_color);

title( ...
    axes_1, ...
    'Convergence of Model-Based GARE Policy Iteration', ...
    'Color',text_color, ...
    'FontName',font_name, ...
    'FontSize',13, ...
    'FontWeight','bold');

legend_1 = legend( ...
    axes_1, ...
    'Value Matrix P', ...
    'Pursuer Gain L', ...
    'Evader Gain K', ...
    'Location','southwest');

set(legend_1, ...
    'Color','w', ...
    'TextColor','k', ...
    'EdgeColor',legend_edge_color, ...
    'FontName',font_name, ...
    'FontSize',10, ...
    'Box','on');

drawnow;

savefig( ...
    figure_1, ...
    fullfile( ...
    results_folder, ...
    'Figure_1_GARE_PI_Convergence.fig'));

exportgraphics( ...
    figure_1, ...
    fullfile( ...
    results_folder, ...
    'Figure_1_GARE_PI_Convergence.png'), ...
    'Resolution',300, ...
    'BackgroundColor','white');

%% ============================================================
%  FIGURE 2: COST-WEIGHTED STATE-DEVIATION RECOVERY
%  ============================================================
%
% The plotted metric is:
%
%   ||d_k||_Q = sqrt(d_k' Q d_k).
%
% Exact compensation is not drawn because its error is at
% double-precision scale. Including it would unnecessarily compress
% the two physically meaningful curves. Its maximum error remains
% reported in the annotation and numerical summary.

time_state = 0:Nsim;

uncompensated_recovery_plot = ...
    weighted_state_deviation(:,2);

estimated_recovery_plot = ...
    weighted_state_deviation(:,3);

% The common initial state gives zero deviation at k = 0.
% Replace only nonpositive display values with NaN so zero is not
% sent to the logarithmic axes. The saved numerical data are unchanged.

uncompensated_recovery_plot( ...
    uncompensated_recovery_plot <= 0) = NaN;

estimated_recovery_plot( ...
    estimated_recovery_plot <= 0) = NaN;

uncompensated_peak = ...
    maximum_weighted_state_deviation(2);

estimated_peak = ...
    maximum_weighted_state_deviation(3);

recovery_lower_reference = ...
    max(0.10*estimated_peak,eps);

recovery_upper_reference = ...
    max(1.20*uncompensated_peak, ...
    10*recovery_lower_reference);

recovery_lower_limit = ...
    10^floor(log10(recovery_lower_reference));

recovery_upper_limit = ...
    10^ceil(log10(recovery_upper_reference));

if ~isfinite(recovery_lower_limit) || ...
        recovery_lower_limit <= 0

    recovery_lower_limit = 1e-6;

end

if ~isfinite(recovery_upper_limit) || ...
        recovery_upper_limit <= recovery_lower_limit

    recovery_upper_limit = ...
        100*recovery_lower_limit;

end

figure_2 = figure( ...
    'Color','w', ...
    'InvertHardcopy','off', ...
    'Renderer','painters', ...
    'Position',[100 100 1000 640], ...
    'Name','Cost-Weighted State-Deviation Recovery');

axes_2 = axes(figure_2);

semilogy( ...
    axes_2, ...
    time_state, ...
    uncompensated_recovery_plot, ...
    '-', ...
    'Color',uncompensated_color, ...
    'LineWidth',1.70);

hold(axes_2,'on');

semilogy( ...
    axes_2, ...
    time_state, ...
    estimated_recovery_plot, ...
    '--', ...
    'Color',estimated_color, ...
    'LineWidth',1.70);

set(axes_2, ...
    'Color','w', ...
    'XColor',axis_color, ...
    'YColor',axis_color, ...
    'FontName',font_name, ...
    'FontSize',font_size, ...
    'LineWidth',0.85, ...
    'Box','on', ...
    'XGrid','off', ...
    'YGrid','on', ...
    'XMinorGrid','off', ...
    'YMinorGrid','off', ...
    'GridColor',grid_color, ...
    'GridAlpha',0.28);

xlim(axes_2,[0,Nsim]);

ylim(axes_2,[ ...
    recovery_lower_limit, ...
    recovery_upper_limit]);

xlabel( ...
    axes_2, ...
    'Time step k', ...
    'Color',axis_color);

ylabel( ...
    axes_2, ...
    '$\|d_k\|_Q=\sqrt{d_k^{\mathrm{T}}Qd_k}$', ...
    'Interpreter','latex', ...
    'Color',axis_color);

title( ...
    axes_2, ...
    'Cost-Weighted State-Deviation Recovery', ...
    'Color',text_color, ...
    'FontName',font_name, ...
    'FontSize',13, ...
    'FontWeight','bold');

legend_2 = legend( ...
    axes_2, ...
    'Without Compensation', ...
    'Estimated Compensation', ...
    'Location','southwest');

set(legend_2, ...
    'Color','w', ...
    'TextColor','k', ...
    'EdgeColor',legend_edge_color, ...
    'FontName',font_name, ...
    'FontSize',10, ...
    'Box','on');

text( ...
    axes_2, ...
    0.98, ...
    0.57, ...
    sprintf( ...
    ['Maximum-Deviation Reduction: %.4f%%\n', ...
     'Exact-Compensation Maximum: %.3e'], ...
    estimated_error_reduction_percent, ...
    maximum_weighted_state_deviation(4)), ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'FontName',font_name, ...
    'FontSize',9.5, ...
    'Color',text_color, ...
    'BackgroundColor',annotation_background, ...
    'EdgeColor',annotation_edge, ...
    'Margin',5);

drawnow;

savefig( ...
    figure_2, ...
    fullfile( ...
    results_folder, ...
    'Figure_2_Cost_Weighted_State_Deviation.fig'));

exportgraphics( ...
    figure_2, ...
    fullfile( ...
    results_folder, ...
    'Figure_2_Cost_Weighted_State_Deviation.png'), ...
    'Resolution',300, ...
    'BackgroundColor','white');

%% ============================================================
%  FIGURE 3: LATE-TIME COMMAND-CHANNEL BIAS COMPENSATION
%  ============================================================
%
% The plot begins after the principal closed-loop transient so the
% persistent command shifts and residual compensation errors remain
% visible.

input_window_start = ...
    round(0.30*Nsim);

input_indices = ...
    (input_window_start+1):Nsim;

input_time = ...
    input_window_start:(Nsim-1);

figure_3 = figure( ...
    'Color','w', ...
    'InvertHardcopy','off', ...
    'Renderer','painters', ...
    'Position',[40 40 1420 850], ...
    'Name','Late-Time Command-Channel Bias Compensation');

layout_3 = tiledlayout( ...
    figure_3, ...
    2,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

%% Pursuer Compensation Mechanism

axes_3a = nexttile(layout_3);

plot( ...
    axes_3a, ...
    input_time, ...
    uP_policy(input_indices,3), ...
    '-', ...
    'Color',policy_color, ...
    'LineWidth',1.65);

hold(axes_3a,'on');

plot( ...
    axes_3a, ...
    input_time, ...
    uP_command_matrix(input_indices,3), ...
    '--', ...
    'Color',command_color, ...
    'LineWidth',1.55);

plot( ...
    axes_3a, ...
    input_time, ...
    uP_actual_matrix(input_indices,3), ...
    '-.', ...
    'Color',realized_color, ...
    'LineWidth',1.55);

yline( ...
    axes_3a, ...
    0, ...
    '-', ...
    'Color',[0.65 0.65 0.65], ...
    'LineWidth',0.8);

set(axes_3a, ...
    'Color','w', ...
    'XColor',axis_color, ...
    'YColor',axis_color, ...
    'FontName',font_name, ...
    'FontSize',font_size, ...
    'LineWidth',0.85, ...
    'Box','on', ...
    'XGrid','off', ...
    'YGrid','on', ...
    'GridColor',grid_color, ...
    'GridAlpha',0.28);

xlim(axes_3a,[input_window_start,Nsim-1]);

ylabel( ...
    axes_3a, ...
    'Pursuer input', ...
    'Color',axis_color);

title( ...
    axes_3a, ...
    'Pursuer: Policy, Commanded, and Realized Inputs', ...
    'Color',text_color, ...
    'FontSize',12, ...
    'FontWeight','bold');

legend_3a = legend( ...
    axes_3a, ...
    'Policy Input', ...
    'Compensated Command', ...
    'Realized Input', ...
    'Location','northeast');

set(legend_3a, ...
    'Color','w', ...
    'TextColor','k', ...
    'EdgeColor',legend_edge_color, ...
    'FontName',font_name, ...
    'FontSize',9, ...
    'Box','on');

text( ...
    axes_3a, ...
    0.97, ...
    0.78, ...
    sprintf( ...
    'Residual Channel Error: %+.3e', ...
    residual_bias_P(3)), ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'FontName',font_name, ...
    'FontSize',9, ...
    'Color',text_color, ...
    'BackgroundColor',annotation_background, ...
    'EdgeColor',annotation_edge, ...
    'Margin',4);

%% Pursuer Realized Input by Case

axes_3b = nexttile(layout_3);

plot( ...
    axes_3b, ...
    input_time, ...
    uP_actual_matrix(input_indices,1), ...
    '-', ...
    'Color',nominal_color, ...
    'LineWidth',1.60);

hold(axes_3b,'on');

plot( ...
    axes_3b, ...
    input_time, ...
    uP_actual_matrix(input_indices,2), ...
    '--', ...
    'Color',uncompensated_color, ...
    'LineWidth',1.55);

plot( ...
    axes_3b, ...
    input_time, ...
    uP_actual_matrix(input_indices,3), ...
    '-.', ...
    'Color',estimated_color, ...
    'LineWidth',1.55);

yline( ...
    axes_3b, ...
    0, ...
    '-', ...
    'Color',[0.65 0.65 0.65], ...
    'LineWidth',0.8);

set(axes_3b, ...
    'Color','w', ...
    'XColor',axis_color, ...
    'YColor',axis_color, ...
    'FontName',font_name, ...
    'FontSize',font_size, ...
    'LineWidth',0.85, ...
    'Box','on', ...
    'XGrid','off', ...
    'YGrid','on', ...
    'GridColor',grid_color, ...
    'GridAlpha',0.28);

xlim(axes_3b,[input_window_start,Nsim-1]);

ylabel( ...
    axes_3b, ...
    'Pursuer input', ...
    'Color',axis_color);

title( ...
    axes_3b, ...
    'Pursuer: Realized Input by Case', ...
    'Color',text_color, ...
    'FontSize',12, ...
    'FontWeight','bold');

legend_3b = legend( ...
    axes_3b, ...
    'Nominal / Exact Compensation', ...
    'Without Compensation', ...
    'Estimated Compensation', ...
    'Location','northeast');

set(legend_3b, ...
    'Color','w', ...
    'TextColor','k', ...
    'EdgeColor',legend_edge_color, ...
    'FontName',font_name, ...
    'FontSize',9, ...
    'Box','on');

%% Evader Compensation Mechanism

axes_3c = nexttile(layout_3);

plot( ...
    axes_3c, ...
    input_time, ...
    uE_policy(input_indices,3), ...
    '-', ...
    'Color',policy_color, ...
    'LineWidth',1.65);

hold(axes_3c,'on');

plot( ...
    axes_3c, ...
    input_time, ...
    uE_command_matrix(input_indices,3), ...
    '--', ...
    'Color',command_color, ...
    'LineWidth',1.55);

plot( ...
    axes_3c, ...
    input_time, ...
    uE_actual_matrix(input_indices,3), ...
    '-.', ...
    'Color',realized_color, ...
    'LineWidth',1.55);

yline( ...
    axes_3c, ...
    0, ...
    '-', ...
    'Color',[0.65 0.65 0.65], ...
    'LineWidth',0.8);

set(axes_3c, ...
    'Color','w', ...
    'XColor',axis_color, ...
    'YColor',axis_color, ...
    'FontName',font_name, ...
    'FontSize',font_size, ...
    'LineWidth',0.85, ...
    'Box','on', ...
    'XGrid','off', ...
    'YGrid','on', ...
    'GridColor',grid_color, ...
    'GridAlpha',0.28);

xlim(axes_3c,[input_window_start,Nsim-1]);

xlabel( ...
    axes_3c, ...
    'Time step k', ...
    'Color',axis_color);

ylabel( ...
    axes_3c, ...
    'Evader input', ...
    'Color',axis_color);

title( ...
    axes_3c, ...
    'Evader: Policy, Commanded, and Realized Inputs', ...
    'Color',text_color, ...
    'FontSize',12, ...
    'FontWeight','bold');

text( ...
    axes_3c, ...
    0.97, ...
    0.93, ...
    sprintf( ...
    'Residual Channel Error: %+.3e', ...
    residual_bias_E(3)), ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'FontName',font_name, ...
    'FontSize',9, ...
    'Color',text_color, ...
    'BackgroundColor',annotation_background, ...
    'EdgeColor',annotation_edge, ...
    'Margin',4);

%% Evader Realized Input by Case

axes_3d = nexttile(layout_3);

plot( ...
    axes_3d, ...
    input_time, ...
    uE_actual_matrix(input_indices,1), ...
    '-', ...
    'Color',nominal_color, ...
    'LineWidth',1.60);

hold(axes_3d,'on');

plot( ...
    axes_3d, ...
    input_time, ...
    uE_actual_matrix(input_indices,2), ...
    '--', ...
    'Color',uncompensated_color, ...
    'LineWidth',1.55);

plot( ...
    axes_3d, ...
    input_time, ...
    uE_actual_matrix(input_indices,3), ...
    '-.', ...
    'Color',estimated_color, ...
    'LineWidth',1.55);

yline( ...
    axes_3d, ...
    0, ...
    '-', ...
    'Color',[0.65 0.65 0.65], ...
    'LineWidth',0.8);

set(axes_3d, ...
    'Color','w', ...
    'XColor',axis_color, ...
    'YColor',axis_color, ...
    'FontName',font_name, ...
    'FontSize',font_size, ...
    'LineWidth',0.85, ...
    'Box','on', ...
    'XGrid','off', ...
    'YGrid','on', ...
    'GridColor',grid_color, ...
    'GridAlpha',0.28);

xlim(axes_3d,[input_window_start,Nsim-1]);

xlabel( ...
    axes_3d, ...
    'Time step k', ...
    'Color',axis_color);

ylabel( ...
    axes_3d, ...
    'Evader input', ...
    'Color',axis_color);

title( ...
    axes_3d, ...
    'Evader: Realized Input by Case', ...
    'Color',text_color, ...
    'FontSize',12, ...
    'FontWeight','bold');

title( ...
    layout_3, ...
    sprintf( ...
    'Late-Time Command-Channel Bias Compensation (k \\geq %d)', ...
    input_window_start), ...
    'Color',text_color, ...
    'FontName',font_name, ...
    'FontSize',13, ...
    'FontWeight','bold');

drawnow;

savefig( ...
    figure_3, ...
    fullfile( ...
    results_folder, ...
    'Figure_3_Command_Channel_Compensation.fig'));

exportgraphics( ...
    figure_3, ...
    fullfile( ...
    results_folder, ...
    'Figure_3_Command_Channel_Compensation.png'), ...
    'Resolution',300, ...
    'BackgroundColor','white');

%% ============================================================
%  FIGURE 4: MONTE CARLO OFFSET-ESTIMATOR VALIDATION
%  ============================================================
%
% Histograms show the distribution of individual offset estimates.
%
% The theoretical interval is the 95-percent interval for one
% calibration estimate. It is not a confidence interval for the
% Monte Carlo sample mean.
%
% The standard error of the Monte Carlo mean is reported separately
% in each annotation.

figure_4 = figure( ...
    'Color','w', ...
    'InvertHardcopy','off', ...
    'Renderer','painters', ...
    'Position',[60 100 1380 640], ...
    'Name','Monte Carlo Offset-Estimator Validation');

layout_4 = tiledlayout( ...
    figure_4, ...
    1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

channel_titles = { ...
    'Pursuer Offset Estimates', ...
    'Evader Offset Estimates'};

channel_xlabels = { ...
    'Estimated pursuer offset', ...
    'Estimated evader offset'};

for channel_index = 1:2

    current_axes = ...
        nexttile(layout_4);

    channel_samples = ...
        monte_carlo_bias_estimates(channel_index,:);

    distribution_values = [ ...
        channel_samples(:);
        bias_true(channel_index);
        bias_estimate(channel_index);
        monte_carlo_bias_mean(channel_index);
        theoretical_bias_95_lower(channel_index);
        theoretical_bias_95_upper(channel_index)];

    distribution_values = ...
        distribution_values(isfinite(distribution_values));

    distribution_minimum = ...
        min(distribution_values);

    distribution_maximum = ...
        max(distribution_values);

    distribution_range = ...
        distribution_maximum-distribution_minimum;

    if distribution_range <= 0

        distribution_range = ...
            max(1e-8, ...
            abs(bias_true(channel_index))*0.01);

    end

    distribution_limits = [ ...
        distribution_minimum ...
        - 0.08*distribution_range, ...
        distribution_maximum ...
        + 0.08*distribution_range];

    histogram_handle = histogram( ...
        current_axes, ...
        channel_samples, ...
        35, ...
        'Normalization','pdf', ...
        'FaceColor',[0.55 0.72 0.86], ...
        'FaceAlpha',0.72, ...
        'EdgeColor','w', ...
        'LineWidth',0.45);

    hold(current_axes,'on');

    density_x = linspace( ...
        distribution_limits(1), ...
        distribution_limits(2), ...
        400);

    density_sigma = ...
        theoretical_bias_std(channel_index);

    if density_sigma <= 0 || ...
            ~isfinite(density_sigma)

        density_sigma = eps;

    end

    theoretical_density = ...
        exp(-0.5*(( ...
        density_x-bias_true(channel_index)) ...
        /density_sigma).^2) ...
        /(density_sigma*sqrt(2*pi));

    density_handle = plot( ...
        current_axes, ...
        density_x, ...
        theoretical_density, ...
        '-', ...
        'Color',theoretical_color, ...
        'LineWidth',1.60);

    true_handle = xline( ...
        current_axes, ...
        bias_true(channel_index), ...
        '-', ...
        'Color',policy_color, ...
        'LineWidth',1.45);

    primary_handle = xline( ...
        current_axes, ...
        bias_estimate(channel_index), ...
        '--', ...
        'Color',estimated_color, ...
        'LineWidth',1.45);

    mean_handle = xline( ...
        current_axes, ...
        monte_carlo_bias_mean(channel_index), ...
        ':', ...
        'Color',nominal_color, ...
        'LineWidth',1.55);

    lower_interval_handle = xline( ...
        current_axes, ...
        theoretical_bias_95_lower(channel_index), ...
        '-.', ...
        'Color',[0.45 0.45 0.45], ...
        'LineWidth',1.10);

    upper_interval_handle = xline( ...
        current_axes, ...
        theoretical_bias_95_upper(channel_index), ...
        '-.', ...
        'Color',[0.45 0.45 0.45], ...
        'LineWidth',1.10);

    set(upper_interval_handle, ...
        'HandleVisibility','off');

    set(current_axes, ...
        'Color','w', ...
        'XColor',axis_color, ...
        'YColor',axis_color, ...
        'FontName',font_name, ...
        'FontSize',font_size, ...
        'LineWidth',0.85, ...
        'Box','on', ...
        'XGrid','off', ...
        'YGrid','on', ...
        'GridColor',grid_color, ...
        'GridAlpha',0.24);

    xlim(current_axes,distribution_limits);

    current_axes.XAxis.Exponent = 0;

    xlabel( ...
        current_axes, ...
        channel_xlabels{channel_index}, ...
        'Color',axis_color);

    ylabel( ...
        current_axes, ...
        'Probability density', ...
        'Color',axis_color);

    title( ...
        current_axes, ...
        channel_titles{channel_index}, ...
        'Color',text_color, ...
        'FontSize',12, ...
        'FontWeight','bold');

    text( ...
        current_axes, ...
        0.98, ...
        0.95, ...
        sprintf( ...
        ['Individual-Estimate SD\n', ...
         'Empirical: %.3e\n', ...
         'Theoretical: %.3e\n', ...
         'SE of Monte Carlo Mean: %.3e'], ...
        monte_carlo_bias_std(channel_index), ...
        theoretical_bias_std(channel_index), ...
        monte_carlo_mean_standard_error(channel_index)), ...
        'Units','normalized', ...
        'HorizontalAlignment','right', ...
        'VerticalAlignment','top', ...
        'FontName',font_name, ...
        'FontSize',8.8, ...
        'Color',text_color, ...
        'BackgroundColor',annotation_background, ...
        'EdgeColor',annotation_edge, ...
        'Margin',5);

    if channel_index == 1

        legend_4 = legend( ...
            current_axes, ...
            [histogram_handle, ...
             density_handle, ...
             true_handle, ...
             primary_handle, ...
             mean_handle, ...
             lower_interval_handle], ...
            'Monte Carlo Estimates', ...
            'Theoretical Density', ...
            'True Offset', ...
            'Primary Estimate', ...
            'Monte Carlo Mean', ...
            'Theoretical 95% Individual-Estimate Interval', ...
            'Location','northwest');

        set(legend_4, ...
            'Color','w', ...
            'TextColor','k', ...
            'EdgeColor',legend_edge_color, ...
            'FontName',font_name, ...
            'FontSize',8.5, ...
            'Box','on');

    end

end

title( ...
    layout_4, ...
    'Monte Carlo Validation of Command-Offset Estimates', ...
    'Color',text_color, ...
    'FontName',font_name, ...
    'FontSize',13, ...
    'FontWeight','bold');

drawnow;

savefig( ...
    figure_4, ...
    fullfile( ...
    results_folder, ...
    'Figure_4_Offset_Estimator_Distributions.fig'));

exportgraphics( ...
    figure_4, ...
    fullfile( ...
    results_folder, ...
    'Figure_4_Offset_Estimator_Distributions.png'), ...
    'Resolution',300, ...
    'BackgroundColor','white');

%% Final Completion Message

fprintf('\n');
fprintf('============================================================\n');
fprintf('GARE POLICY-ITERATION STUDY COMPLETED SUCCESSFULLY\n');
fprintf('============================================================\n');
fprintf('State metric:                              sqrt(d''*Q*d)\n');
fprintf('State weight:                              Q = eye(3)\n');
fprintf('Policy-iteration count:                    %d\n',iteration);
fprintf('Maximum uncompensated deviation:           %.12e\n', ...
    maximum_weighted_state_deviation(2));
fprintf('Maximum estimated-compensation deviation: %.12e\n', ...
    maximum_weighted_state_deviation(3));
fprintf('Maximum exact-compensation deviation:      %.12e\n', ...
    maximum_weighted_state_deviation(4));
fprintf('Estimated-compensation error reduction:    %.6f %%\n', ...
    estimated_error_reduction_percent);
fprintf('Maximum analytical mismatch:               %.12e\n', ...
    max(maximum_analytical_mismatch));

fprintf('\nPublication figures generated:\n');
fprintf('1. Convergence of Model-Based GARE Policy Iteration\n');
fprintf('2. Cost-Weighted State-Deviation Recovery\n');
fprintf('3. Late-Time Command-Channel Bias Compensation\n');
fprintf('4. Monte Carlo Validation of Command-Offset Estimates\n');

fprintf('\nFigures and numerical results were saved to:\n');
fprintf('%s\n',results_folder);
fprintf('============================================================\n');